# SPDX-FileCopyrightText: 2023 Davide Paro
#
# SPDX-License-Identifier: MIT

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
        - id: reuse
          name: Add SPDX headers
          args:
              [
                  annotate,
                  --copyright=Davide Paro,
                  --license=MIT,
                  --skip-unrecognised,
              ]
          pass_filenames: true
        - id: reuse
          name: reuse lint
          args: [lint]

  # - repo: https://github.com/cheshirekow/cmake-format-precommit
  #   rev: v0.6.10
  #   hooks:
  #   - id: cmake-format
  #   - id: cmake-lint

  - repo: local
    hooks:
    - id: cmake
      name: Build and test project with ASAN
      description: Build and test project with ASAN
      entry: cmake --workspace --preset debug-asan
      language: 'system'
      types: [c, c++, cmake]
      pass_filenames: false
